# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geoprocessing.ui'
#
# Created: Fri Mar 20 10:35:56 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Geoprocessing(object):
    def setupUi(self, Geoprocessing):
        Geoprocessing.setObjectName("Geoprocessing")
        Geoprocessing.resize(421, 473)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Geoprocessing.sizePolicy().hasHeightForWidth())
        Geoprocessing.setSizePolicy(sizePolicy)
        self.gridlayout = QtGui.QGridLayout(Geoprocessing)
        self.gridlayout.setMargin(9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.gridlayout1 = QtGui.QGridLayout()
        self.gridlayout1.setMargin(0)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btnAbout = QtGui.QPushButton(Geoprocessing)
        self.btnAbout.setObjectName("btnAbout")
        self.hboxlayout.addWidget(self.btnAbout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.btnOk = QtGui.QPushButton(Geoprocessing)
        self.btnOk.setObjectName("btnOk")
        self.hboxlayout.addWidget(self.btnOk)
        self.btnExit = QtGui.QPushButton(Geoprocessing)
        self.btnExit.setObjectName("btnExit")
        self.hboxlayout.addWidget(self.btnExit)
        self.gridlayout1.addLayout(self.hboxlayout, 1, 0, 1, 1)
        self.gridlayout2 = QtGui.QGridLayout()
        self.gridlayout2.setMargin(0)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.frame = QtGui.QFrame(Geoprocessing)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.gridlayout3 = QtGui.QGridLayout(self.frame)
        self.gridlayout3.setMargin(9)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.gridlayout4 = QtGui.QGridLayout()
        self.gridlayout4.setMargin(0)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(0)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.hboxlayout1.addWidget(self.label)
        self.cmbLayerB = QtGui.QComboBox(self.frame)
        self.cmbLayerB.setEnabled(False)
        self.cmbLayerB.setObjectName("cmbLayerB")
        self.hboxlayout1.addWidget(self.cmbLayerB)
        self.gridlayout4.addLayout(self.hboxlayout1, 6, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem1, 9, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem2, 4, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setSpacing(6)
        self.hboxlayout2.setMargin(0)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.hboxlayout2.addWidget(self.label_6)
        self.lineEditParameter = QtGui.QLineEdit(self.frame)
        self.lineEditParameter.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditParameter.sizePolicy().hasHeightForWidth())
        self.lineEditParameter.setSizePolicy(sizePolicy)
        self.lineEditParameter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditParameter.setCursorPosition(0)
        self.lineEditParameter.setObjectName("lineEditParameter")
        self.hboxlayout2.addWidget(self.lineEditParameter)
        self.gridlayout4.addLayout(self.hboxlayout2, 4, 0, 1, 1)
        self.hboxlayout3 = QtGui.QHBoxLayout()
        self.hboxlayout3.setSpacing(6)
        self.hboxlayout3.setMargin(0)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.hboxlayout3.addWidget(self.label_2)
        self.cmbLayerA = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbLayerA.sizePolicy().hasHeightForWidth())
        self.cmbLayerA.setSizePolicy(sizePolicy)
        self.cmbLayerA.setObjectName("cmbLayerA")
        self.hboxlayout3.addWidget(self.cmbLayerA)
        self.gridlayout4.addLayout(self.hboxlayout3, 2, 0, 1, 1)
        self.hboxlayout4 = QtGui.QHBoxLayout()
        self.hboxlayout4.setSpacing(6)
        self.hboxlayout4.setMargin(0)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.lblItems = QtGui.QLabel(self.frame)
        self.lblItems.setObjectName("lblItems")
        self.hboxlayout4.addWidget(self.lblItems)
        self.cmbAttribA = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbAttribA.sizePolicy().hasHeightForWidth())
        self.cmbAttribA.setSizePolicy(sizePolicy)
        self.cmbAttribA.setObjectName("cmbAttribA")
        self.hboxlayout4.addWidget(self.cmbAttribA)
        self.gridlayout4.addLayout(self.hboxlayout4, 8, 0, 1, 1)
        self.hboxlayout5 = QtGui.QHBoxLayout()
        self.hboxlayout5.setSpacing(6)
        self.hboxlayout5.setMargin(0)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.hboxlayout5.addWidget(self.label_4)
        self.cmbFunction = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbFunction.sizePolicy().hasHeightForWidth())
        self.cmbFunction.setSizePolicy(sizePolicy)
        self.cmbFunction.setObjectName("cmbFunction")
        self.cmbFunction.addItem(QtCore.QString())
        self.cmbFunction.addItem(QtCore.QString())
# dq edit
#        self.cmbFunction.addItem(QtCore.QString())
#        self.cmbFunction.addItem(QtCore.QString())
#        self.cmbFunction.addItem(QtCore.QString())
#        self.cmbFunction.addItem(QtCore.QString())
#        self.cmbFunction.addItem(QtCore.QString())
# dq endedit
        self.hboxlayout5.addWidget(self.cmbFunction)
        self.gridlayout4.addLayout(self.hboxlayout5, 0, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout4.addItem(spacerItem3, 6, 0, 1, 1)
        self.gridlayout3.addLayout(self.gridlayout4, 0, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem4, 3, 0, 1, 1)
        self.hboxlayout6 = QtGui.QHBoxLayout()
        self.hboxlayout6.setSpacing(6)
        self.hboxlayout6.setMargin(0)
        self.hboxlayout6.setObjectName("hboxlayout6")
        self.chkBoxAddShape = QtGui.QCheckBox(self.frame)
        self.chkBoxAddShape.setChecked(True)
        self.chkBoxAddShape.setObjectName("chkBoxAddShape")
        self.hboxlayout6.addWidget(self.chkBoxAddShape)
        self.gridlayout3.addLayout(self.hboxlayout6, 4, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem5, 5, 0, 1, 1)
        self.hboxlayout7 = QtGui.QHBoxLayout()
        self.hboxlayout7.setSpacing(6)
        self.hboxlayout7.setMargin(0)
        self.hboxlayout7.setObjectName("hboxlayout7")
        self.progressBar = QtGui.QProgressBar(self.frame)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.hboxlayout7.addWidget(self.progressBar)
        self.gridlayout3.addLayout(self.hboxlayout7, 8, 0, 1, 1)
        self.hboxlayout8 = QtGui.QHBoxLayout()
        self.hboxlayout8.setSpacing(6)
        self.hboxlayout8.setMargin(0)
        self.hboxlayout8.setObjectName("hboxlayout8")
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.hboxlayout8.addWidget(self.label_3)
        self.lineEditShapeDir = QtGui.QLineEdit(self.frame)
        self.lineEditShapeDir.setObjectName("lineEditShapeDir")
        self.hboxlayout8.addWidget(self.lineEditShapeDir)
        self.btnBrowse = QtGui.QPushButton(self.frame)
        self.btnBrowse.setObjectName("btnBrowse")
        self.hboxlayout8.addWidget(self.btnBrowse)
        self.gridlayout3.addLayout(self.hboxlayout8, 6, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem6, 7, 0, 1, 1)
        self.hboxlayout9 = QtGui.QHBoxLayout()
        self.hboxlayout9.setSpacing(6)
        self.hboxlayout9.setMargin(0)
        self.hboxlayout9.setObjectName("hboxlayout9")
        self.gridlayout3.addLayout(self.hboxlayout9, 8, 0, 1, 1)
        self.hboxlayout10 = QtGui.QHBoxLayout()
        self.hboxlayout10.setSpacing(6)
        self.hboxlayout10.setMargin(0)
        self.hboxlayout10.setObjectName("hboxlayout10")
        self.chkBoxSelectedFeatures = QtGui.QCheckBox(self.frame)
        self.chkBoxSelectedFeatures.setEnabled(False)
        self.chkBoxSelectedFeatures.setObjectName("chkBoxSelectedFeatures")
        self.hboxlayout10.addWidget(self.chkBoxSelectedFeatures)
        self.gridlayout3.addLayout(self.hboxlayout10, 2, 0, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridlayout3.addItem(spacerItem7, 1, 0, 1, 1)
        self.gridlayout2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridlayout1.addLayout(self.gridlayout2, 0, 0, 1, 1)
        self.gridlayout.addLayout(self.gridlayout1, 0, 0, 1, 1)

        self.retranslateUi(Geoprocessing)
        QtCore.QMetaObject.connectSlotsByName(Geoprocessing)

# dq edit the second parameter to adjust the names in the box - dq #
    def retranslateUi(self, Geoprocessing):
        Geoprocessing.setWindowTitle(QtGui.QApplication.translate("Geoprocessing", "Urban Analysis Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAbout.setText(QtGui.QApplication.translate("Geoprocessing", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOk.setText(QtGui.QApplication.translate("Geoprocessing", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("Geoprocessing", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Geoprocessing", "City Center Shapefile:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Geoprocessing", "Parameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Geoprocessing", "Population Density Shapefile:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblItems.setText(QtGui.QApplication.translate("Geoprocessing", "Attribute:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Geoprocessing", "Function:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(0, QtGui.QApplication.translate("Geoprocessing", "Select a function ...", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(1, QtGui.QApplication.translate("Geoprocessing", "Population Density Gradient", None, QtGui.QApplication.UnicodeUTF8))
        
        # the combobox (cmb) has been commented out about. As these functions are called later, they are currently left intact 
        self.cmbFunction.setItemText(2, QtGui.QApplication.translate("Geoprocessing", "Convex Hull", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(3, QtGui.QApplication.translate("Geoprocessing", "Difference A - B", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(4, QtGui.QApplication.translate("Geoprocessing", "Dissolve", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(5, QtGui.QApplication.translate("Geoprocessing", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbFunction.setItemText(6, QtGui.QApplication.translate("Geoprocessing", "Union", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxAddShape.setText(QtGui.QApplication.translate("Geoprocessing", "Add Layer to Map?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Geoprocessing", "Save as:", None, QtGui.QApplication.UnicodeUTF8))
        
# dq test
#        self.chkBoxAddShape.setText(QtGui.QApplication.translate("Geoprocessing", "test?", None, QtGui.QApplication.UnicodeUTF8))
# dq end test        
        self.btnBrowse.setText(QtGui.QApplication.translate("Geoprocessing", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxSelectedFeatures.setText(QtGui.QApplication.translate("Geoprocessing", "Dissolve Result", None, QtGui.QApplication.UnicodeUTF8))

